plugin: aws_ec2
regions:
  - ap-south-1
filters:
  # This matches the tag you set in your Terraform SonarQube module
  tag:Name: SonarQube-Server 
compose:
  # Forces Ansible to connect using the private IP inside the VPC
  ansible_host: private_ip_address
